/***********************************************************************
**
**   messagehandler.h
**
**   This file is part of Cumulus
**
************************************************************************
**
**   Copyright (c):  2005 by Axel Pauli (axel@kflog.org)
**
**   This program is free software; you can redistribute it and/or modify
**   it under the terms of the GNU General Public License as published by
**   the Free Software Foundation; either version 2 of the License, or
**   (at your option) any later version.
**
**   $Id$
**
***********************************************************************/

#ifndef MESSAGEHANDLER_H
#define MESSAGEHANDLER_H

/**
 * @short handler for cumulus message
 * @author Axel Pauli
 *
 * This class is used to handle the messages generated by cumulus through
 * using qDebug, qWarning, qFatal.
 *
 **/

#include <QApplication>

void messageHandler(QtMsgType type, const char* msg);

#endif
