# $Id$
# Makefile to call the debian packge install target from the cumulus area.
# Found no other way to get it running

install:
	cd ../../..;$(MAKE) -f Makefile.Maemo4 DESTDIR=$(DESTDIR) dpkg_install
