# $Id: makefile 2853 2008-08-05 20:08:47Z axel $
# Makefile to call the debian packge install target from the cumulus area.
# Found no other way to get it running

install:
	cd ../../..; $(MAKE) -f  Makefile.Maemo5 DESTDIR=$(DESTDIR) dpkg_install
