# $Id: makefile 3865 2010-03-16 19:33:22Z axel $
# Makefile to call the debian packge install target from the cumulus area.
# Found no other way to get it running

install:
	cd ../../..;$(MAKE) -f Makefile.Maemo4 DESTDIR=$(DESTDIR) dpkg_install_lang
